baseURL = '/'
languageCode = 'en-us'
title = 'Sequoia Fabrica Makerspace'

buildFuture = true
buildDrafts = false
pagination.pagerSize = 12

DefaultContentLanguage = 'en'
defaultContentLanguage = 'en'
pluralizelisttitles = 'false'

refLinksErrorLevel = 'WARNING'
refLinksNotFoundURL = '/'

timeout = 60000

rssLimit = 3

enableInlineShortcodes = true

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.parser.attribute]
    block = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'onesenterprise'
    tabWidth = 4

[permalinks]
  posts = '/:year/:month/:slugorfilename/'
  categories = '/:slug/'

[params]
  author = 'Camille Teicheira'
  newsletter = 'https://dashboard.mailerlite.com/forms/1197290/139047052633965606/share'
  description = 'This is a solar-powered website, which means it sometimes goes offline'

[menu]
  [[menu.main]]
    identifier = 'about'
    name = 'About'
    url = 'https://sequoiafabrica.org/docs/about'
    weight = 1
  [[menu.main]]
    identifier = 'mainsitetitle'
    name = 'sequoiafabrica.org'
    url = 'https://sequoiafabrica.org'
    weight = 2
  [[menu.main]]
    identifier = 'donate'
    name = 'Donate'
    url = 'https://opencollective.com/sequoia-fabrica'
    weight = 3

[taxonomies]
  author = 'authors'
  tag = 'tags'
  category = 'categories'
  translator = 'translators'
  lang = 'languages'

[related]
  includeNewer = true
  threshold = 80
  toLower = false
  [[related.indices]]
    name = 'tags'
    weight = 100
  [[related.indices]]
    name = 'lang'
    weight = 80
