baseURL = '/'
languageCode = 'en-us'
title = 'Sequoia Fabrica Makerspace'

buildFuture = true
buildDrafts = false
pagination.pagerSize = 12

DefaultContentLanguage = 'en'
defaultContentLanguage = 'en'
pluralizelisttitles = 'false'

refLinksErrorLevel = 'WARNING'
refLinksNotFoundURL = '/'

timeout = 60000

rssLimit = 3

enableInlineShortcodes = true

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.parser.attribute]
    block = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'onesenterprise'
    tabWidth = 4

[permalinks]
  posts = '/:year/:month/:slugorfilename/'
  categories = '/:slug/'

[params]
  author = 'Camille Teicheira'
  newsletter = 'https://dashboard.mailerlite.com/forms/1197290/139047052633965606/share'
  description = 'This is a solar-powered website, which means it sometimes goes offline'
  donate = 'https://opencollective.com/sequoia-fabrica'
  events = 'https://bookwhen.com/sequoiafabrica#focus=ev-s5jb-20250313160000'
  wiki = 'https://wiki.sequoiafabrica.org/wiki/Main_Page'
  email = 'info@sequoiafabrica.org'
  mastadon = ''
  instagram = ''
  tiktok = ''

[menu]
  [[menu.main]]
    identifier = 'about'
    name = 'About'
    url = '/about'
    weight = 1
  [[menu.main]]
    identifier = 'events'
    name = 'Events'
    url = 'https://bookwhen.com/sequoiafabrica'
    weight = 2
  [[menu.main]]
    identifier = 'donate'
    name = 'Donate'
    url = 'https://opencollective.com/sequoia-fabrica'
    weight = 3
  [[menu.main]]
    identifier = 'membership'
    name = 'Membership'
    url = '/membership'
    weight = 4
  [[menu.main]]
    identifier = 'faq'
    name = 'FAQ'
    url = '/faq'
    weight = 5
  [[menu.main]]
    identifier = 'partner'
    name = 'Partner'
    url = '/partner'
    weight = 6
  [[menu.main]]
    identifier = 'contact'
    name = 'Contact'
    url = '/contact'
    weight = 7
  [[menu.main]]
    identifier = 'blog'
    name = 'Blog'
    url = '/posts'
    weight = 8


[languages]
  [languages.en]
    languageName = 'English'
    weight = 1
  [languages.fr]
    languageName = 'Français'
    weight = 2
  [languages.de]
    languageName = 'Deutsch'
    weight = 3
  [languages.nl]
    languageName = 'Nederlands'
    weight = 4
  [languages.es]
    languageName = 'Español'
    weight = 5
  [languages.it]
    languageName = 'Italiano'
    weight = 6
  [languages.pt]
    languageName = 'Português'
    weight = 7
  [languages.pl]
    languageName = 'Polski'
    weight = 8
  [languages.ar]
    languageName = 'العربية'
    languagedirection = 'rtl'
    weight = 9
  [languages.vn]
    languageName = 'Tiếng Việt'
    weight = 10
  [languages.ko]
    languageName = '한국어'
    weight = 11

[taxonomies]
  author = 'authors'
  tag = 'tags'
  category = 'categories'
  translator = 'translators'
  lang = 'languages'

[related]
  includeNewer = true
  threshold = 80
  toLower = false
  [[related.indices]]
    name = 'tags'
    weight = 100
  [[related.indices]]
    name = 'lang'
    weight = 80
