name: Test build hugo site

on: [push]

jobs:
  build:
    name: Build Hugo Site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true # Use extended version for SCSS/asset pipeline

      - name: Build the site
        run: hugo --minify

      - name: Check for build success
        run: |
          if [ ! -d "public" ]; then
            echo "Build failed: 'public' directory not found"
            exit 1
          fi
