name: Test build hugo site

on: [push]

jobs:
  build:
    name: Build Hugo Site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Install Dart Sass
        run: sudo snap install dart-sass

      - name: Build the site
        run: hugo --minify

      - name: Check for build success
        run: |
          if [ ! -d "public" ]; then
            echo "Build failed: 'public' directory not found"
            exit 1
          fi
